# Generated by Django 5.1.2 on 2024-12-14 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_movie_poster_path_alter_playlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='backdrop_url',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster_path',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tmdb_id',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='name',
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='movies',
            field=models.ManyToManyField(blank=True, to='streaming.movie'),
        ),
    ]
